version: "3"

services:
    postgres:
        image: postgres:17.4
        ports:
            - "5532:5432"
        volumes:
            - ./storage/development/postgres/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=passpilot
            - POSTGRES_USER=passpilot
            - POSTGRES_DB=passpilot
        extra_hosts:
            - "host.docker.internal:host-gateway"

    redis-cache:
        image: redis:latest
        ports:
            - "5579:6379"
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - ./storage/development/redis/data:/data
        extra_hosts:
            - "host.docker.internal:host-gateway"

    minio:
        image: minio/minio:latest
        ports:
            - "9500:9000"
            - "9501:9001"
        volumes:
            - ./storage/development/minio/data:/data
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
            - MINIO_BROWSER_REDIRECT_URL=http://localhost:9501
            - MINIO_DOMAIN=localhost
        command: server /data --console-address ":9001" --address ":9000"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3
        extra_hosts:
            - "host.docker.internal:host-gateway"
